# Generated by Django 4.2.4 on 2023-08-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='links',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='details',
            field=models.CharField(max_length=999),
        ),
    ]
